# Generated by Django 6.0.6 on 2026-07-09 06:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BehaviorAnomaly',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anomaly_type', models.CharField(choices=[('unusual_login_time', 'Unusual Login Time'), ('unusual_ip', 'Unusual IP Address'), ('unusual_command', 'Unusual Command'), ('high_activity', 'High Activity Volume'), ('new_host', 'New Host Access'), ('privilege_escalation', 'Privilege Escalation Attempt'), ('data_exfil', 'Potential Data Exfiltration')], max_length=50)),
                ('description', models.TextField()),
                ('severity', models.CharField(default='medium', max_length=20)),
                ('confidence', models.FloatField(default=0.5)),
                ('metadata', models.JSONField(default=dict)),
                ('is_resolved', models.BooleanField(default=False)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserBehaviorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('avg_login_time', models.TimeField(null=True)),
                ('common_ips', models.JSONField(default=list)),
                ('common_hosts', models.JSONField(default=list)),
                ('login_frequency_per_day', models.FloatField(default=0)),
                ('common_commands', models.JSONField(default=list)),
                ('sudo_frequency', models.FloatField(default=0)),
                ('anomaly_score', models.FloatField(default=0)),
                ('risk_level', models.CharField(default='low', max_length=20)),
                ('total_events_analyzed', models.IntegerField(default=0)),
                ('last_analyzed', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
