# Generated by Django 6.0.6 on 2026-07-07 17:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('agents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('rule_type', models.CharField(choices=[('threshold', 'Threshold'), ('anomaly', 'Anomaly'), ('correlation', 'Correlation'), ('pattern', 'Pattern Match'), ('frequency', 'Frequency'), ('sequence', 'Sequence'), ('blacklist', 'Blacklist'), ('whitelist', 'Whitelist')], max_length=50)),
                ('conditions', models.JSONField()),
                ('actions', models.JSONField(default=dict)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('tags', models.JSONField(default=list)),
                ('use_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rule Template',
                'verbose_name_plural': 'Rule Templates',
                'ordering': ['-use_count'],
            },
        ),
        migrations.CreateModel(
            name='DetectionRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('rule_type', models.CharField(choices=[('threshold', 'Threshold'), ('anomaly', 'Anomaly'), ('correlation', 'Correlation'), ('pattern', 'Pattern Match'), ('frequency', 'Frequency'), ('sequence', 'Sequence'), ('blacklist', 'Blacklist'), ('whitelist', 'Whitelist')], default='threshold', max_length=50)),
                ('conditions', models.JSONField(help_text='\n        Example threshold rule:\n        {\n            "event_type": "FAILED_LOGIN",\n            "timeframe_minutes": 5,\n            "threshold": 5,\n            "group_by": ["source_ip"],\n            "filters": {\n                "severity": ["medium", "high", "critical"],\n                "source": ["ssh"]\n            }\n        }\n        \n        Example correlation rule:\n        {\n            "events": [\n                {"event_type": "FAILED_LOGIN", "count": 5, "timeframe_minutes": 5},\n                {"event_type": "SUCCESSFUL_LOGIN", "count": 1, "timeframe_minutes": 5}\n            ],\n            "group_by": ["source_ip"],\n            "require_all": true\n        }\n        ')),
                ('actions', models.JSONField(default=dict, help_text='\n        {\n            "create_alert": true,\n            "alert_title": "Brute Force Attack Detected",\n            "alert_severity": "high",\n            "alert_category": "security",\n            "auto_escalate": true,\n            "notify_channels": ["email", "slack"],\n            "create_incident": false,\n            "block_ip": false\n        }\n        ')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('category', models.CharField(default='security', max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('testing', 'Testing'), ('disabled', 'Disabled')], default='active', max_length=20)),
                ('priority', models.IntegerField(default=100)),
                ('cooldown_minutes', models.IntegerField(default=5)),
                ('times_triggered', models.IntegerField(default=0)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('alerts_generated', models.IntegerField(default=0)),
                ('apply_to_all_agents', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_groups', models.ManyToManyField(blank=True, related_name='rules', to='agents.agentgroup')),
                ('agents', models.ManyToManyField(blank=True, related_name='rules', to='agents.agent')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detection_rules', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Detection Rule',
                'verbose_name_plural': 'Detection Rules',
                'ordering': ['priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RuleExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('execution_time', models.FloatField(blank=True, null=True)),
                ('is_triggered', models.BooleanField(default=False)),
                ('matched_count', models.IntegerField(default=0)),
                ('events_analyzed', models.IntegerField(default=0)),
                ('context', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='rules.detectionrule')),
            ],
            options={
                'verbose_name': 'Rule Execution',
                'verbose_name_plural': 'Rule Executions',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='detectionrule',
            index=models.Index(fields=['status', 'rule_type'], name='rules_detec_status_40c5cf_idx'),
        ),
        migrations.AddIndex(
            model_name='detectionrule',
            index=models.Index(fields=['severity'], name='rules_detec_severit_840b7c_idx'),
        ),
        migrations.AddIndex(
            model_name='detectionrule',
            index=models.Index(fields=['organization'], name='rules_detec_organiz_6a4fdc_idx'),
        ),
        migrations.AddIndex(
            model_name='ruleexecution',
            index=models.Index(fields=['rule', 'executed_at'], name='rules_rulee_rule_id_d623c6_idx'),
        ),
        migrations.AddIndex(
            model_name='ruleexecution',
            index=models.Index(fields=['is_triggered'], name='rules_rulee_is_trig_708f78_idx'),
        ),
    ]
