# Generated by Django 6.0.6 on 2026-07-07 17:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_size', models.IntegerField()),
                ('status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='received', max_length=20)),
                ('logs_processed', models.IntegerField(default=0)),
                ('events_generated', models.IntegerField(default=0)),
                ('errors_encountered', models.IntegerField(default=0)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('error_details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_batches', to='agents.agent')),
            ],
            options={
                'verbose_name': 'Log Batch',
                'verbose_name_plural': 'Log Batches',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['agent', 'created_at'], name='logs_logbat_agent_i_40e6ce_idx'), models.Index(fields=['status', 'created_at'], name='logs_logbat_status_b2b13a_idx')],
            },
        ),
        migrations.CreateModel(
            name='RawLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('source', models.CharField(choices=[('auth', 'Authentication'), ('syslog', 'System Log'), ('nginx_access', 'Nginx Access'), ('nginx_error', 'Nginx Error'), ('docker', 'Docker'), ('django', 'Django'), ('application', 'Application'), ('custom', 'Custom')], db_index=True, max_length=50)),
                ('log_level', models.CharField(blank=True, choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], db_index=True, max_length=20, null=True)),
                ('raw_message', models.TextField()),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('hostname', models.CharField(blank=True, max_length=255, null=True)),
                ('service', models.CharField(blank=True, max_length=100, null=True)),
                ('is_parsed', models.BooleanField(db_index=True, default=False)),
                ('parsed_at', models.DateTimeField(blank=True, null=True)),
                ('parse_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('log_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_logs', to='agents.agent')),
            ],
            options={
                'verbose_name': 'Raw Log',
                'verbose_name_plural': 'Raw Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['agent', 'timestamp'], name='logs_rawlog_agent_i_fb1d91_idx'), models.Index(fields=['source', 'timestamp'], name='logs_rawlog_source_fe29b6_idx'), models.Index(fields=['log_level', 'timestamp'], name='logs_rawlog_log_lev_29c3db_idx'), models.Index(fields=['is_parsed', 'created_at'], name='logs_rawlog_is_pars_073f5b_idx')],
            },
        ),
    ]
