# Generated by Django 6.0.6 on 2026-07-09 05:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_user_avatar_user_bio_user_browser_notifications_and_more'),
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('node_type', models.CharField(choices=[('server', 'Server'), ('container', 'Container'), ('service', 'Service'), ('database', 'Database'), ('load_balancer', 'Load Balancer'), ('firewall', 'Firewall'), ('external', 'External')], max_length=50)),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('x_position', models.FloatField(default=0)),
                ('y_position', models.FloatField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(default='online', max_length=20)),
                ('cpu_usage', models.FloatField(null=True)),
                ('memory_usage', models.FloatField(null=True)),
                ('connection_count', models.IntegerField(default=0)),
                ('alert_count', models.IntegerField(default=0)),
                ('risk_score', models.FloatField(default=0)),
                ('metadata', models.JSONField(default=dict)),
                ('labels', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agent')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
            ],
            options={
                'ordering': ['node_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NetworkScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='running', max_length=20)),
                ('nodes_found', models.IntegerField(default=0)),
                ('edges_found', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='NetworkEdge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('edge_type', models.CharField(choices=[('http', 'HTTP/HTTPS'), ('ssh', 'SSH'), ('database', 'Database'), ('api', 'API'), ('proxy', 'Proxy'), ('dns', 'DNS'), ('unknown', 'Unknown')], default='unknown', max_length=50)),
                ('protocol', models.CharField(blank=True, max_length=20)),
                ('port', models.IntegerField(null=True)),
                ('bytes_transferred', models.BigIntegerField(default=0)),
                ('request_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('latency_ms', models.FloatField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(default='healthy', max_length=20)),
                ('first_seen', models.DateTimeField(null=True)),
                ('last_seen', models.DateTimeField(null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='topology.networknode')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='topology.networknode')),
            ],
            options={
                'unique_together': {('source', 'target', 'port')},
            },
        ),
    ]
