# Generated by Django 6.0.6 on 2026-07-09 05:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_user_avatar_user_bio_user_browser_notifications_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForensicTimeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('host_identifier', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimelineEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('event', 'Security Event'), ('alert', 'Alert'), ('incident', 'Incident'), ('action', 'User Action'), ('system', 'System Change'), ('network', 'Network Activity'), ('file', 'File Change'), ('process', 'Process Activity')], max_length=50)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(default='info', max_length=20)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(default=dict)),
                ('timeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='forensics.forensictimeline')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
