# Generated by Django 6.0.6 on 2026-07-09 04:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_user_avatar_user_bio_user_browser_notifications_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playbook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('trigger_type', models.CharField(choices=[('alert', 'On Alert'), ('threshold', 'On Threshold'), ('schedule', 'On Schedule'), ('manual', 'Manual Only')], max_length=50)),
                ('trigger_conditions', models.JSONField(default=dict)),
                ('actions', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('times_executed', models.IntegerField(default=0)),
                ('last_executed', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
            ],
            options={
                'ordering': ['-times_executed'],
            },
        ),
        migrations.CreateModel(
            name='PlaybookExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='running', max_length=20)),
                ('trigger_event', models.JSONField(default=dict)),
                ('results', models.JSONField(default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('playbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='playbooks.playbook')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
