# Generated by Django 6.0.6 on 2026-07-07 17:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('hostname', models.CharField(max_length=255)),
                ('token', models.CharField(db_index=True, max_length=255, unique=True)),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('agent_type', models.CharField(choices=[('linux', 'Linux Server'), ('docker', 'Docker Host'), ('kubernetes', 'Kubernetes Node'), ('custom', 'Custom')], default='linux', max_length=20)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('degraded', 'Degraded'), ('error', 'Error')], db_index=True, default='offline', max_length=20)),
                ('os_info', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=50, null=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('monitored_logs', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_interval', models.IntegerField(default=30)),
                ('missed_heartbeats', models.IntegerField(default=0)),
                ('cpu_usage', models.FloatField(blank=True, null=True)),
                ('memory_usage', models.FloatField(blank=True, null=True)),
                ('disk_usage', models.FloatField(blank=True, null=True)),
                ('network_status', models.CharField(blank=True, max_length=50, null=True)),
                ('total_logs_collected', models.BigIntegerField(default=0)),
                ('total_events_generated', models.BigIntegerField(default=0)),
                ('total_alerts_triggered', models.BigIntegerField(default=0)),
                ('uptime_seconds', models.BigIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('last_error_time', models.DateTimeField(blank=True, null=True)),
                ('error_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
                'ordering': ['-last_heartbeat'],
            },
        ),
        migrations.CreateModel(
            name='AgentConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monitored_logs', models.JSONField(blank=True, default=list)),
                ('log_batch_size', models.IntegerField(default=100)),
                ('log_buffer_max_size', models.IntegerField(default=10000)),
                ('log_level_filter', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', max_length=20)),
                ('heartbeat_interval', models.IntegerField(default=30)),
                ('metrics_interval', models.IntegerField(default=60)),
                ('log_collection_interval', models.IntegerField(default=10)),
                ('max_retries', models.IntegerField(default=5)),
                ('retry_delay', models.IntegerField(default=5)),
                ('retry_backoff', models.FloatField(default=2.0)),
                ('notify_on_offline', models.BooleanField(default=True)),
                ('notify_on_error', models.BooleanField(default=True)),
                ('notify_on_high_cpu', models.BooleanField(default=False)),
                ('cpu_threshold', models.FloatField(default=90.0)),
                ('notify_on_high_memory', models.BooleanField(default=False)),
                ('memory_threshold', models.FloatField(default=90.0)),
                ('enable_compression', models.BooleanField(default=True)),
                ('enable_encryption', models.BooleanField(default=True)),
                ('enable_docker_monitoring', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='agents.agent')),
            ],
            options={
                'verbose_name': 'Agent Configuration',
                'verbose_name_plural': 'Agent Configurations',
            },
        ),
        migrations.CreateModel(
            name='AgentGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agents', models.ManyToManyField(related_name='groups', to='agents.agent')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_groups', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Agent Group',
                'verbose_name_plural': 'Agent Groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AgentHeartbeat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('cpu_usage', models.FloatField(blank=True, null=True)),
                ('cpu_cores', models.IntegerField(blank=True, null=True)),
                ('cpu_model', models.CharField(blank=True, max_length=255, null=True)),
                ('memory_usage', models.FloatField(blank=True, null=True)),
                ('memory_total', models.BigIntegerField(blank=True, null=True)),
                ('memory_used', models.BigIntegerField(blank=True, null=True)),
                ('memory_free', models.BigIntegerField(blank=True, null=True)),
                ('disk_usage', models.FloatField(blank=True, null=True)),
                ('disk_total', models.BigIntegerField(blank=True, null=True)),
                ('disk_used', models.BigIntegerField(blank=True, null=True)),
                ('disk_free', models.BigIntegerField(blank=True, null=True)),
                ('disk_partitions', models.JSONField(blank=True, default=list)),
                ('network_io', models.JSONField(blank=True, default=dict)),
                ('network_interfaces', models.JSONField(blank=True, default=list)),
                ('network_connections', models.IntegerField(blank=True, null=True)),
                ('process_count', models.IntegerField(blank=True, null=True)),
                ('zombie_processes', models.IntegerField(blank=True, null=True)),
                ('uptime', models.FloatField(blank=True, null=True)),
                ('load_average', models.JSONField(blank=True, default=dict)),
                ('boot_time', models.DateTimeField(blank=True, null=True)),
                ('buffer_size', models.IntegerField(blank=True, null=True)),
                ('logs_collected', models.IntegerField(default=0)),
                ('events_generated', models.IntegerField(default=0)),
                ('errors_encountered', models.IntegerField(default=0)),
                ('is_healthy', models.BooleanField(default=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heartbeats', to='agents.agent')),
            ],
            options={
                'verbose_name': 'Agent Heartbeat',
                'verbose_name_plural': 'Agent Heartbeats',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['agent_id'], name='agents_agen_agent_i_f18e23_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['token'], name='agents_agen_token_d32e0d_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['status'], name='agents_agen_status_4212bf_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['organization'], name='agents_agen_organiz_d03747_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['hostname'], name='agents_agen_hostnam_71bd35_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['last_heartbeat'], name='agents_agen_last_he_b23ff2_idx'),
        ),
        migrations.AddIndex(
            model_name='agentheartbeat',
            index=models.Index(fields=['agent', 'timestamp'], name='agents_agen_agent_i_5eb4c5_idx'),
        ),
        migrations.AddIndex(
            model_name='agentheartbeat',
            index=models.Index(fields=['timestamp'], name='agents_agen_timesta_3107bd_idx'),
        ),
    ]
