# Generated by Django 6.0.6 on 2026-07-09 04:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_user_avatar_user_bio_user_browser_notifications_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPReputation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(db_index=True, unique=True)),
                ('reputation_score', models.IntegerField(default=50)),
                ('abuse_confidence', models.IntegerField(default=0)),
                ('is_tor', models.BooleanField(default=False)),
                ('is_proxy', models.BooleanField(default=False)),
                ('is_vpn', models.BooleanField(default=False)),
                ('is_datacenter', models.BooleanField(default=False)),
                ('country', models.CharField(max_length=100, null=True)),
                ('isp', models.CharField(max_length=255, null=True)),
                ('domain', models.CharField(max_length=255, null=True)),
                ('usage_type', models.CharField(max_length=100, null=True)),
                ('last_reported', models.DateTimeField(null=True)),
                ('report_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['abuse_confidence'],
            },
        ),
        migrations.CreateModel(
            name='ThreatScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_ip', models.GenericIPAddressField(db_index=True)),
                ('event_type', models.CharField(max_length=100, null=True)),
                ('threat_score', models.FloatField(default=0)),
                ('frequency_score', models.FloatField(default=0)),
                ('severity_score', models.FloatField(default=0)),
                ('pattern_score', models.FloatField(default=0)),
                ('reputation_score', models.FloatField(default=0)),
                ('total_events', models.IntegerField(default=0)),
                ('unique_event_types', models.IntegerField(default=0)),
                ('first_seen', models.DateTimeField(null=True)),
                ('last_seen', models.DateTimeField(null=True)),
                ('is_known_attacker', models.BooleanField(default=False)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='low', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
            ],
            options={
                'ordering': ['-threat_score'],
                'indexes': [models.Index(fields=['source_ip'], name='threat_inte_source__cb24c0_idx'), models.Index(fields=['risk_level'], name='threat_inte_risk_le_6feb99_idx'), models.Index(fields=['threat_score'], name='threat_inte_threat__fb3952_idx')],
                'unique_together': {('source_ip', 'organization')},
            },
        ),
    ]
