# Generated by Django 6.0.6 on 2026-07-07 17:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('category', models.CharField(choices=[('authentication', 'Authentication'), ('authorization', 'Authorization'), ('network', 'Network'), ('system', 'System'), ('application', 'Application'), ('container', 'Container'), ('security', 'Security'), ('compliance', 'Compliance')], db_index=True, default='system', max_length=50)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='info', max_length=20)),
                ('confidence', models.FloatField(default=1.0)),
                ('source', models.CharField(db_index=True, max_length=50)),
                ('service', models.CharField(blank=True, max_length=50, null=True)),
                ('source_ip', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('source_port', models.IntegerField(blank=True, null=True)),
                ('source_hostname', models.CharField(blank=True, max_length=255, null=True)),
                ('target_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('target_port', models.IntegerField(blank=True, null=True)),
                ('target_hostname', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('tags', models.JSONField(default=list)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('is_analyzed', models.BooleanField(db_index=True, default=False)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='agents.agent')),
                ('parent_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_events', to='events.event')),
                ('raw_log', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='logs.rawlog')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EventCorrelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('correlation_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('confidence', models.FloatField(default=0.5)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('events', models.ManyToManyField(related_name='correlations', to='events.event')),
            ],
            options={
                'verbose_name': 'Event Correlation',
                'verbose_name_plural': 'Event Correlations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_type', 'timestamp'], name='events_even_event_t_19b40a_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['source_ip', 'timestamp'], name='events_even_source__8b6831_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['username', 'timestamp'], name='events_even_usernam_11d72f_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['agent', 'timestamp'], name='events_even_agent_i_5b12b9_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['severity', 'timestamp'], name='events_even_severit_cc88bd_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['category', 'timestamp'], name='events_even_categor_b33171_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_analyzed', 'timestamp'], name='events_even_is_anal_58531e_idx'),
        ),
    ]
