# Generated by Django 6.0.6 on 2026-07-09 05:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_user_avatar_user_bio_user_browser_notifications_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Honeypot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('protocol', models.CharField(choices=[('ssh', 'SSH'), ('http', 'HTTP'), ('ftp', 'FTP'), ('mysql', 'MySQL'), ('telnet', 'Telnet')], max_length=20)),
                ('port', models.IntegerField()),
                ('host', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
            ],
        ),
        migrations.CreateModel(
            name='HoneypotInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_ip', models.GenericIPAddressField(db_index=True)),
                ('source_port', models.IntegerField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('interaction_type', models.CharField(max_length=50)),
                ('payload', models.TextField(blank=True)),
                ('headers', models.JSONField(default=dict)),
                ('is_malicious', models.BooleanField(default=True)),
                ('threat_level', models.CharField(default='high', max_length=20)),
                ('attack_pattern', models.CharField(blank=True, max_length=100)),
                ('honeypot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='honeypot.honeypot')),
            ],
        ),
    ]
