# Generated by Django 6.0.6 on 2026-07-08 14:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_user_avatar_user_bio_user_browser_notifications_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('LOGIN_FAILED', 'Login Failed'), ('EXPORT', 'Export'), ('VIEW', 'View'), ('CONFIG_CHANGE', 'Configuration Change'), ('PERMISSION_CHANGE', 'Permission Change'), ('STATUS_CHANGE', 'Status Change'), ('2FA_SETUP', '2FA Setup'), ('2FA_DISABLE', '2FA Disable'), ('PASSWORD_CHANGE', 'Password Change'), ('AGENT_REGISTER', 'Agent Register'), ('AGENT_DELETE', 'Agent Delete'), ('RULE_EXECUTE', 'Rule Execute'), ('ALERT_CREATE', 'Alert Create'), ('INCIDENT_CREATE', 'Incident Create'), ('REPORT_GENERATE', 'Report Generate')], max_length=50)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=20)),
                ('description', models.TextField()),
                ('object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(default=dict)),
                ('changes', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='audit_audit_user_id_e8be02_idx'), models.Index(fields=['action', 'timestamp'], name='audit_audit_action_2a1328_idx'), models.Index(fields=['organization', 'timestamp'], name='audit_audit_organiz_47f094_idx'), models.Index(fields=['content_type', 'object_id'], name='audit_audit_content_4c2ead_idx')],
            },
        ),
    ]
