# Generated by Django 6.0.6 on 2026-07-09 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_user_avatar_user_bio_user_browser_notifications_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MitreTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technique_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('tactic', models.CharField(max_length=100)),
                ('platform', models.CharField(blank=True, max_length=100)),
                ('data_sources', models.JSONField(default=list)),
                ('detection_recommendations', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['technique_id'],
            },
        ),
        migrations.CreateModel(
            name='EventTechniqueMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100, unique=True)),
                ('confidence', models.FloatField(default=0.8)),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mitre.mitretechnique')),
            ],
            options={
                'ordering': ['event_type'],
            },
        ),
        migrations.CreateModel(
            name='MitreCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_events', models.IntegerField(default=0)),
                ('last_detected', models.DateTimeField(null=True)),
                ('is_covered', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mitre.mitretechnique')),
            ],
            options={
                'unique_together': {('technique', 'organization')},
            },
        ),
    ]
