# Generated by Django 6.0.6 on 2026-07-09 04:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_user_avatar_user_bio_user_browser_notifications_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('export_type', models.CharField(choices=[('events', 'Events'), ('alerts', 'Alerts'), ('incidents', 'Incidents'), ('report', 'Report'), ('audit', 'Audit Log')], max_length=50)),
                ('format', models.CharField(choices=[('csv', 'CSV'), ('json', 'JSON'), ('pdf', 'PDF')], default='csv', max_length=20)),
                ('frequency', models.CharField(choices=[('hourly', 'Every Hour'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20)),
                ('destination', models.CharField(choices=[('email', 'Email'), ('s3', 'Amazon S3'), ('webhook', 'Webhook'), ('local', 'Local Storage')], default='email', max_length=20)),
                ('destination_config', models.JSONField(default=dict)),
                ('filters', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(null=True)),
                ('next_run', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
            ],
            options={
                'ordering': ['next_run'],
            },
        ),
        migrations.CreateModel(
            name='ExportRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('file_size', models.BigIntegerField(null=True)),
                ('record_count', models.IntegerField(null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='scheduler.exportschedule')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
