# Generated by Django 6.0.6 on 2026-07-07 17:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('alerts', '0001_initial'),
        ('events', '0001_initial'),
        ('rules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('incident_type', models.CharField(choices=[('brute_force', 'Brute Force Attack'), ('malware', 'Malware Infection'), ('data_breach', 'Data Breach'), ('ddos', 'DDoS Attack'), ('unauthorized_access', 'Unauthorized Access'), ('privilege_escalation', 'Privilege Escalation'), ('system_compromise', 'System Compromise'), ('policy_violation', 'Policy Violation'), ('insider_threat', 'Insider Threat'), ('phishing', 'Phishing Attack'), ('ransomware', 'Ransomware'), ('other', 'Other')], default='other', max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('triaging', 'Triaging'), ('investigating', 'Investigating'), ('containment', 'Containment'), ('eradication', 'Eradication'), ('recovery', 'Recovery'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('false_positive', 'False Positive')], db_index=True, default='new', max_length=20)),
                ('priority', models.CharField(choices=[('p1', 'P1 - Critical'), ('p2', 'P2 - High'), ('p3', 'P3 - Medium'), ('p4', 'P4 - Low')], default='p3', max_length=3)),
                ('assigned_team', models.CharField(blank=True, max_length=255, null=True)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('correlation_confidence', models.FloatField(default=0.0)),
                ('affected_systems', models.JSONField(blank=True, default=list)),
                ('affected_users', models.JSONField(blank=True, default=list)),
                ('impact_scope', models.CharField(choices=[('single_host', 'Single Host'), ('multiple_hosts', 'Multiple Hosts'), ('network_wide', 'Network Wide'), ('organization_wide', 'Organization Wide')], default='single_host', max_length=50)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('source_hostname', models.CharField(blank=True, max_length=255, null=True)),
                ('attack_vector', models.CharField(blank=True, max_length=255, null=True)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('artifacts', models.JSONField(blank=True, default=list)),
                ('indicators_of_compromise', models.JSONField(blank=True, default=list)),
                ('detected_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('contained_at', models.DateTimeField(blank=True, null=True)),
                ('eradicated_at', models.DateTimeField(blank=True, null=True)),
                ('recovered_at', models.DateTimeField(blank=True, null=True)),
                ('resolution', models.TextField(blank=True)),
                ('resolution_type', models.CharField(blank=True, choices=[('contained', 'Contained'), ('eradicated', 'Eradicated'), ('mitigated', 'Mitigated'), ('false_positive', 'False Positive'), ('not_applicable', 'Not Applicable')], max_length=50, null=True)),
                ('root_cause', models.TextField(blank=True)),
                ('lessons_learned', models.TextField(blank=True)),
                ('time_to_detect', models.IntegerField(blank=True, null=True)),
                ('time_to_contain', models.IntegerField(blank=True, null=True)),
                ('time_to_resolve', models.IntegerField(blank=True, null=True)),
                ('sla_deadline', models.DateTimeField(blank=True, null=True)),
                ('is_overdue', models.BooleanField(default=False)),
                ('is_critical', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('alerts', models.ManyToManyField(blank=True, related_name='incidents', to='alerts.alert')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL)),
                ('correlation_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='rules.detectionrule')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_incidents', to=settings.AUTH_USER_MODEL)),
                ('events', models.ManyToManyField(blank=True, related_name='incidents', to='events.event')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note_type', models.CharField(choices=[('investigation', 'Investigation Note'), ('analysis', 'Analysis'), ('action', 'Action Taken'), ('finding', 'Finding'), ('recommendation', 'Recommendation'), ('general', 'General Note')], default='general', max_length=50)),
                ('content', models.TextField()),
                ('is_private', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='incidents.incident')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incident Note',
                'verbose_name_plural': 'Incident Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentTimeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('alert', 'Alert Generated'), ('event', 'Event Occurred'), ('action', 'Action Taken'), ('comment', 'Comment Added'), ('status_change', 'Status Changed'), ('evidence', 'Evidence Added'), ('assignment', 'Assignment Changed'), ('escalation', 'Escalation'), ('notification', 'Notification Sent'), ('system', 'System Action')], max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='incidents.incident')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incident Timeline',
                'verbose_name_plural': 'Incident Timelines',
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['status', 'severity'], name='incidents_i_status_85e429_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['organization', 'created_at'], name='incidents_i_organiz_6cc078_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['assigned_to', 'status'], name='incidents_i_assigne_f40e13_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['incident_type'], name='incidents_i_inciden_337dba_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['correlation_id'], name='incidents_i_correla_99f64e_idx'),
        ),
        migrations.AddIndex(
            model_name='incidenttimeline',
            index=models.Index(fields=['incident', 'timestamp'], name='incidents_i_inciden_c51168_idx'),
        ),
        migrations.AddIndex(
            model_name='incidenttimeline',
            index=models.Index(fields=['entry_type'], name='incidents_i_entry_t_73a803_idx'),
        ),
    ]
