# Generated by Django 6.0.6 on 2026-07-09 06:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='🏅', max_length=10)),
                ('criteria', models.JSONField(default=dict)),
                ('points', models.IntegerField(default=50)),
            ],
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.CharField(max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('rankings', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnalystProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_points', models.IntegerField(default=0)),
                ('weekly_points', models.IntegerField(default=0)),
                ('monthly_points', models.IntegerField(default=0)),
                ('alerts_resolved', models.IntegerField(default=0)),
                ('incidents_closed', models.IntegerField(default=0)),
                ('threats_detected', models.IntegerField(default=0)),
                ('playbooks_executed', models.IntegerField(default=0)),
                ('response_time_avg', models.FloatField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('title', models.CharField(default='Junior Analyst', max_length=100)),
                ('achievements', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
