# Generated by Django 6.0.6 on 2026-07-09 05:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_user_avatar_user_bio_user_browser_notifications_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetRiskScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_name', models.CharField(max_length=255)),
                ('asset_type', models.CharField(max_length=50)),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('overall_risk', models.FloatField(default=0)),
                ('threat_risk', models.FloatField(default=0)),
                ('vulnerability_risk', models.FloatField(default=0)),
                ('exposure_risk', models.FloatField(default=0)),
                ('impact_risk', models.FloatField(default=0)),
                ('recent_attacks', models.IntegerField(default=0)),
                ('open_alerts', models.IntegerField(default=0)),
                ('critical_events', models.IntegerField(default=0)),
                ('exposed_ports', models.JSONField(default=list)),
                ('running_services', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
            ],
            options={
                'ordering': ['-overall_risk'],
            },
        ),
    ]
