# apps/playbooks/engine.py
import logging
from django.utils import timezone
from apps.audit.models import log_action

logger = logging.getLogger(__name__)

class PlaybookEngine:
    """Executes automated playbook actions"""
    
    def execute_playbook(self, playbook, trigger_event=None):
        """Execute a playbook's actions"""
        from apps.playbooks.models import PlaybookExecution
        
        execution = PlaybookExecution.objects.create(
            playbook=playbook,
            status='running',
            trigger_event=trigger_event or {},
        )
        
        results = []
        
        try:
            for i, action in enumerate(playbook.actions):
                result = self._execute_action(action, trigger_event)
                results.append({
                    'step': i + 1,
                    'action': action.get('type'),
                    'success': result.get('success', False),
                    'message': result.get('message', ''),
                })
                
                # Stop on failure if configured
                if not result.get('success') and action.get('stop_on_failure', False):
                    execution.status = 'failed'
                    break
            
            if execution.status != 'failed':
                execution.status = 'completed'
                execution.completed_at = timezone.now()
            
            execution.results = results
            execution.save()
            
            playbook.times_executed += 1
            playbook.last_executed = timezone.now()
            playbook.save()
            
            # Audit log
            log_action(
                user=None,
                action='CONFIG_CHANGE',
                description=f'Playbook "{playbook.name}" executed: {execution.status}',
                obj=playbook,
                severity='info',
                metadata={'execution_id': str(execution.id), 'status': execution.status},
            )
            
            return execution
        
        except Exception as e:
            logger.error(f"Playbook execution failed: {e}")
            execution.status = 'failed'
            execution.results = results
            execution.save()
            return execution
    
    def _execute_action(self, action, trigger_event):
        """Execute a single playbook action"""
        action_type = action.get('type')
        config = action.get('config', {})
        
        try:
            if action_type == 'block_ip':
                return self._block_ip(config.get('ip'))
            
            elif action_type == 'create_alert':
                return self._create_alert(config, trigger_event)
            
            elif action_type == 'create_incident':
                return self._create_incident(config, trigger_event)
            
            elif action_type == 'send_notification':
                return self._send_notification(config, trigger_event)
            
            elif action_type == 'update_agent':
                return self._update_agent(config)
            
            elif action_type == 'webhook':
                return self._call_webhook(config, trigger_event)
            
            elif action_type == 'wait':
                import time
                time.sleep(config.get('seconds', 5))
                return {'success': True, 'message': f'Waited {config.get("seconds")}s'}
            
            else:
                return {'success': False, 'message': f'Unknown action type: {action_type}'}
        
        except Exception as e:
            return {'success': False, 'message': str(e)}
    
    def _block_ip(self, ip):
        """Block an IP address (placeholder - integrate with firewall)"""
        from apps.threat_intel.models import IPReputation
        
        IPReputation.objects.update_or_create(
            ip_address=ip,
            defaults={'abuse_confidence': 100, 'reputation_score': 0}
        )
        
        logger.info(f"IP blocked: {ip}")
        return {'success': True, 'message': f'IP {ip} added to blocklist'}
    
    def _create_alert(self, config, trigger_event):
        """Create an alert"""
        from apps.alerts.models import Alert
        
        alert = Alert.objects.create(
            title=config.get('title', 'Playbook Alert'),
            description=config.get('description', 'Auto-generated by playbook'),
            severity=config.get('severity', 'high'),
            source='playbook',
            category=config.get('category', 'security'),
        )
        
        return {'success': True, 'message': f'Alert created: {alert.id}'}
    
    def _create_incident(self, config, trigger_event):
        """Create an incident"""
        from apps.incidents.models import Incident
        
        incident = Incident.objects.create(
            title=config.get('title', 'Playbook Incident'),
            description=config.get('description', 'Auto-generated by playbook'),
            severity=config.get('severity', 'high'),
            incident_type=config.get('incident_type', 'other'),
        )
        
        return {'success': True, 'message': f'Incident created: {incident.id}'}
    
    def _send_notification(self, config, trigger_event):
        """Send a notification"""
        from apps.notifications.service import NotificationService
        
        service = NotificationService()
        service.send_notification(
            title=config.get('title', 'Playbook Notification'),
            message=config.get('message', 'Action triggered by playbook'),
            priority=config.get('priority', 'high'),
            trigger_type='playbook',
        )
        
        return {'success': True, 'message': 'Notification sent'}
    
    def _update_agent(self, config):
        """Update agent configuration"""
        return {'success': True, 'message': 'Agent update queued'}
    
    def _call_webhook(self, config, trigger_event):
        """Call external webhook"""
        import requests
        
        url = config.get('url')
        if not url:
            return {'success': False, 'message': 'No webhook URL configured'}
        
        response = requests.post(url, json=trigger_event, timeout=10)
        return {'success': response.ok, 'message': f'Webhook returned {response.status_code}'}