# Generated by Django 6.0.6 on 2026-07-09 05:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_user_avatar_user_bio_user_browser_notifications_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceControl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('control_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(max_length=100)),
                ('mapped_events', models.JSONField(default=list)),
                ('mapped_rules', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceFramework',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evidence_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('data', models.JSONField(default=dict)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='compliance.compliancecontrol')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
            ],
        ),
        migrations.AddField(
            model_name='compliancecontrol',
            name='framework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='compliance.complianceframework'),
        ),
        migrations.AlterUniqueTogether(
            name='compliancecontrol',
            unique_together={('framework', 'control_id')},
        ),
    ]
